import 'knowledge_models.dart';

final List<IndustryIntelligence> industryIntelligenceRepo = [
  const IndustryIntelligence(
    id: 'ind_banking_finance',
    industryName: 'Banking & Financial Services',
    businessChallenges: [
      'Regulatory compliance (RBI, SEBI)',
      'Customer service expectations and hyper-personalization',
      'Distributed branch operations and unified communications',
      'Workforce coordination for field agents and collections',
      'Data sovereignty and privacy mandates',
      'Rising operational costs due to legacy systems',
      'Fraud detection and real-time transaction monitoring',
    ],
    technologyChallenges: [
      'Secure communication across distributed networks',
      'Branch connectivity reliability and uptime (SD-WAN needs)',
      'Workforce Mobility',
      'Centralized management of distributed IT infrastructure',
      'Cloud migration risks regarding data residency',
      'Integrating legacy core banking systems with modern APIs',
    ],
    recommendedProducts: [
      'Airtel Corporate Postpaid',
      'Airtel IQ Business Connect',
      'Airtel SD-WAN',
      'Airtel Secure Internet',
      'Airtel Cloud',
      'Airtel SIP Trunking',
      'Airtel Contact Center as a Service',
      'Airtel Global Voice',
    ],
    discoveryQuestions: [
      'How are your branches currently connected to the core banking application?',
      'What happens when a branch experiences a network outage during peak hours?',
      'How do you ensure customer communications (SMS/Voice) remain compliant with local regulations?',
      'What is your current strategy for migrating legacy workloads to the cloud while maintaining data sovereignty?',
      'How is workforce mobility managed for your wealth managers and loan officers?',
      'How are you handling voice recording and communication compliance for your field sales teams?',
      'How do you manage the bandwidth requirements for your ATMs and remote kiosks?',
      'How many different vendors are you currently managing across your branch network and security perimeter?',
      'How quickly can you provision a new branch network today?',
      'What security frameworks are you currently enforcing for remote employee access?',
      'How do you handle peak customer service volumes during tax season or major market events?',
      'Is your current contact center integrated seamlessly with your CRM?',
    ],
    objections: [
      'Security concerns regarding public cloud migration',
      'Compliance concerns with CPaaS providers',
      'Integration complexity with our legacy core banking system',
      'We already have an established MPLS network that works fine',
      'Data residency rules prevent us from using global solutions',
    ],
    salesOpportunities: [
      'Branch network modernization (SD-WAN replacement of MPLS)',
      'Omnichannel customer engagement (Airtel IQ)',
      'Secure remote workforce connectivity (Corporate Postpaid + Secure VPN)',
      'Data center colocation and disaster recovery (Nxtra)',
    ],
  ),
  const IndustryIntelligence(
    id: 'ind_retail',
    industryName: 'Retail',
    businessChallenges: [
      'Multi-store operations and consistency',
      'High staff turnover in retail locations',
      'Seasonal workforce spikes requiring rapid provisioning',
      'Omnichannel customer engagement and loyalty',
      'Supply chain visibility',
      'Inventory management across distributed locations',
    ],
    technologyChallenges: [
      'Store communication and secure POS connectivity',
      'Field workforce coordination for merchandising',
      'Employee onboarding and rapid device provisioning',
      'Managing Wi-Fi networks for both staff and guests',
      'Integrating e-commerce platforms with physical store inventory',
    ],
    recommendedProducts: [
      'Airtel Corporate Postpaid',
      'Airtel IQ Business Connect',
      'Airtel SD-WAN',
      'Airtel Managed Wi-Fi',
      'Airtel IoT',
    ],
    discoveryQuestions: [
      'How do your retail stores currently connect their POS systems to the central inventory database?',
      'What happens to store operations if the primary internet connection fails?',
      'How do you manage and secure guest Wi-Fi across all your retail locations?',
      'How are operational updates and merchandising guidelines shared with store managers?',
      'How quickly can you spin up connectivity for a new pop-up store?',
      'How are you currently getting visibility into store footfall and real-time inventory movement?',
      'How do you handle the surge in communication and connectivity needs during the holiday season?',
      'How do you ensure consistent customer communication across SMS, WhatsApp, and Voice?',
      'What is your process for provisioning corporate devices to temporary seasonal staff?',
      'How are you currently tracking your supply chain and delivery fleets?',
    ],
    objections: [
      'We have thin margins and cannot justify premium connectivity',
      'Store managers are not technical enough to handle new equipment',
      'We use local broadband providers for our stores because it is cheaper',
      'Changing our POS network architecture is too risky right now',
    ],
    salesOpportunities: [
      'Store connectivity standardization (SD-WAN/Managed Wi-Fi)',
      'Customer loyalty campaigns (Airtel IQ CPaaS)',
      'Asset tracking and fleet management (Airtel IoT)',
      'Rapid pop-up store connectivity (5G/4G Enterprise routers)',
    ],
  ),
  const IndustryIntelligence(
    id: 'ind_manufacturing',
    industryName: 'Manufacturing',
    businessChallenges: [
      'Plant coordination across global or national sites',
      'Field workforce management and safety',
      'Operational Efficiency',
      'Supply chain bottlenecks',
      'Predictive Maintenance',
    ],
    technologyChallenges: [
      'Site communication in remote or harsh environments',
      'Workforce Mobility',
      'Connecting legacy industrial equipment to the cloud (Industry 4.0)',
      'Ensuring low latency for automated machinery',
      'Protecting intellectual property from cyber threats',
    ],
    recommendedProducts: [
      'Airtel Corporate Postpaid',
      'Airtel SD-WAN',
      'Airtel IoT',
      'Airtel 5G for Enterprise',
      'Airtel Secure Internet',
      'Airtel Cloud',
    ],
    discoveryQuestions: [
      'How are your production sites currently communicating with headquarters?',
      'What is the financial impact of an hour of network downtime on the factory floor?',
      'How are you currently implementing Industry 4.0 or IoT initiatives?',
      'Are you facing latency issues with automated guided vehicles (AGVs) on the floor?',
      'How do managers communicate securely with field service teams?',
      'What is your strategy for predictive maintenance of critical machinery?',
      'How do you secure your OT (Operational Technology) networks from IT network vulnerabilities?',
      'How do you manage connectivity for factories located in remote, hard-to-reach areas?',
      'What bottlenecks are you hitting with your current factory floor Wi-Fi when trying to deploy automation or AGVs?',
      'How do you track the location and status of high-value assets during transit?',
    ],
    objections: [
      'Our factories are in remote areas where connectivity is fundamentally poor',
      'We cannot risk moving OT data to the public cloud',
      'IoT deployment seems too complex and fragmented',
      'We do not have the internal skills to manage a Private 5G network',
    ],
    salesOpportunities: [
      'Factory floor automation (Private 5G / IoT)',
      'Secure site-to-site connectivity (SD-WAN / MPLS)',
      'Edge computing for real-time analytics (Airtel Cloud)',
      'Remote site connectivity (VSAT / Enterprise LTE)',
    ],
  ),
  const IndustryIntelligence(
    id: 'ind_logistics',
    industryName: 'Logistics',
    businessChallenges: [
      'Fleet coordination and route optimization',
      'Real-time communication with drivers',
      'Distributed operations across warehouses and hubs',
      'Fuel cost management',
      'Last-mile delivery efficiency',
      'SLA compliance with large enterprise customers',
    ],
    technologyChallenges: [
      'Driver connectivity across varying network coverage zones',
      'Field workforce management and device control',
      'Operational visibility and real-time tracking (IoT)',
      'Warehouse Wi-Fi coverage and scanner connectivity',
      'Integrating disjointed supply chain management systems',
    ],
    recommendedProducts: [
      'Airtel Corporate Postpaid',
      'Airtel IQ Business Connect',
      'Airtel IoT',
      'Airtel Managed Wi-Fi',
      'Airtel SD-WAN',
    ],
    discoveryQuestions: [
      'How do your dispatch teams communicate with drivers on the road?',
      'What happens when a delivery driver loses cellular coverage?',
      'How are you currently tracking your fleet and high-value cargo in real-time?',
      'How are you currently managing connectivity blackspots in your large warehouses that disrupt barcode scanning?',
      'How do you manage and secure the mobile devices issued to your delivery staff?',
      'Are you able to automatically update customers via SMS/WhatsApp on their delivery status?',
      'How do you connect your remote distribution hubs to your central ERP system?',
      'What is your process for managing telecom billing for thousands of distributed drivers?',
      'How do you monitor driver behavior and vehicle diagnostics (telematics)?',
    ],
    objections: [
      'We already use GPS trackers from a specialized vendor',
      'Drivers prefer to use their personal phones (BYOD) rather than corporate devices',
      'Warehouse Wi-Fi is too difficult to maintain due to metal racks blocking signals',
      'Margins are too thin for premium SD-WAN solutions at small hubs',
    ],
    salesOpportunities: [
      'End-to-end fleet tracking (Airtel IoT/Telematics)',
      'Automated customer delivery notifications (Airtel IQ)',
      'Warehouse connectivity modernization (Managed Wi-Fi & SD-WAN)',
      'Unified mobility management for drivers (Corporate Postpaid + MDM)',
    ],
  ),
  const IndustryIntelligence(
    id: 'ind_healthcare',
    industryName: 'Healthcare',
    businessChallenges: [
      'Patient data privacy and HIPAA compliance',
      'Telemedicine adoption and reliability',
      'Hospital operational efficiency',
      'Coordination between doctors, staff, and patients',
      'Managing rising healthcare delivery costs',
    ],
    technologyChallenges: [
      'Secure and compliant communication of medical records',
      'Reliable connectivity for life-saving medical devices (IoT)',
      'High-bandwidth requirements for transmitting large imaging files (MRI/CT)',
      'Campus-wide seamless Wi-Fi for staff and patients',
      'Securing the network against ransomware attacks',
    ],
    recommendedProducts: [
      'Airtel Secure Internet',
      'Airtel Cloud',
      'Airtel IQ Business Connect',
      'Airtel Managed Wi-Fi',
      'Airtel Leased Line',
      'Airtel IoT',
    ],
    discoveryQuestions: [
      'How do you ensure patient data remains secure during telemedicine consultations?',
      'What happens if your primary internet connection drops while accessing cloud-based EHR (Electronic Health Records)?',
      'How are doctors and nurses currently communicating sensitive patient updates?',
      'How are you isolating and securing connected medical devices from the rest of the hospital network?',
      'How do you manage appointment reminders and patient follow-ups at scale?',
      'Are you facing bandwidth constraints when transferring large radiology images between facilities?',
      'How do you ensure seamless Wi-Fi roaming across your hospital campus without dead zones?',
      'What is your disaster recovery and data backup strategy against ransomware?',
      'How are you tracking expensive mobile medical equipment (e.g., portable ultrasounds) within the facility?',
    ],
    objections: [
      'Our strict compliance rules prevent us from using public cloud solutions',
      'We cannot risk migrating our critical network; downtime could cost lives',
      'Doctors refuse to use new communication apps; they prefer WhatsApp',
      'Our budget is strictly allocated to medical equipment, not IT infrastructure',
    ],
    salesOpportunities: [
      'Patient engagement and telehealth (Airtel IQ)',
      'Secure, high-bandwidth hospital connectivity (Leased Lines / SD-WAN)',
      'Medical asset tracking (Airtel IoT)',
      'Compliant healthcare data hosting (Nxtra Data Centers)',
    ],
  ),
  const IndustryIntelligence(
    id: 'ind_education',
    industryName: 'Education',
    businessChallenges: [
      'Transitioning to hybrid and remote learning models',
      'Student engagement and retention',
      'Campus safety and emergency communication',
      'Managing administrative costs',
    ],
    technologyChallenges: [
      'Providing reliable connectivity across massive campuses',
      'Securing networks against student-driven cyber threats (e.g., DDoS)',
      'High bandwidth demands in dormitories and lecture halls',
      'Integrating legacy Student Information Systems (SIS)',
    ],
    recommendedProducts: [
      'Airtel Managed Wi-Fi',
      'Airtel Secure Internet',
      'Airtel Cloud',
      'Airtel IQ Business Connect',
      'Airtel SIP Trunking',
    ],
    discoveryQuestions: [
      'How are you handling the massive Wi-Fi density requirements in large lecture halls?',
      'What is your strategy for protecting the university network against DDoS attacks or malware?',
      'How do you communicate emergency alerts to all students and staff instantly?',
      'How are you currently managing and unifying the IT infrastructure across your various campus locations?',
      'How do you support remote or hybrid learning for students lacking reliable internet access?',
      'What happens to your network performance during exam weeks or registration periods?',
      'How are you managing the transition of your physical servers to the cloud?',
      'How do you handle prospective student inquiries and admissions communications at scale?',
    ],
    objections: [
      'We are a public institution bound by strict procurement and budget cycles',
      'We already have an established campus network vendor',
      'Cloud migration is too expensive for our current budget',
    ],
    salesOpportunities: [
      'Campus-wide network modernization (Managed Wi-Fi)',
      'Admissions and student engagement (Airtel IQ CPaaS)',
      'Network security and DDoS protection (Secure Internet)',
      'E-learning infrastructure hosting (Airtel Cloud / Nxtra)',
    ],
  ),
  const IndustryIntelligence(
    id: 'ind_it_ites',
    industryName: 'IT & ITES',
    businessChallenges: [
      'Enabling a permanent Work-From-Anywhere (WFA) workforce',
      'Maintaining global delivery models and SLAs',
      'Client data security and compliance (ISO, SOC2)',
      'Managing employee attrition and onboarding',
    ],
    technologyChallenges: [
      'Ensuring enterprise-grade security on home broadband connections',
      'High-performance connectivity to global data centers',
      'Cloud cost optimization and multi-cloud management',
      'Zero-trust network access for distributed developers',
    ],
    recommendedProducts: [
      'Airtel Work From Anywhere Solutions',
      'Airtel SD-WAN',
      'Airtel Cloud',
      'Airtel Leased Line',
      'Airtel SIP Trunking',
      'Airtel Contact Center as a Service',
    ],
    discoveryQuestions: [
      'How do you ensure your remote developers have secure, enterprise-grade connectivity at home?',
      'What challenges are you facing with your current VPN infrastructure in terms of latency?',
      'How are you connecting your India delivery centers to your clients in the US/UK?',
      'Are you struggling with the complexity and costs of managing multiple public cloud environments?',
      'How quickly can you provision secure connectivity for a new BPO facility?',
      'What is your disaster recovery strategy if a major delivery center goes offline?',
      'How are you handling voice compliance and quality for your international contact center agents?',
      'How do you enforce Zero Trust network access for your distributed workforce?',
      'What percentage of your operational expenditure is tied up in underutilized data center space?',
    ],
    objections: [
      'We are a tech company, we build and manage these networks ourselves',
      'Our clients dictate which cloud providers and networks we must use',
      'We have heavily invested in our current MPLS backbone and won’t rip-and-replace',
    ],
    salesOpportunities: [
      'Remote workforce connectivity (WFA solutions)',
      'Global connectivity backbone (International Private Leased Circuits - IPLC)',
      'Contact center modernization (CCaaS / SIP Trunking)',
      'Multi-cloud networking and colocation (Nxtra)',
    ],
  ),
  const IndustryIntelligence(
    id: 'ind_ecommerce',
    industryName: 'E-Commerce',
    businessChallenges: [
      'Managing massive traffic spikes during sale events',
      'Customer acquisition and retention costs',
      'Last-mile delivery optimization and tracking',
      'Fraud prevention and payment security',
    ],
    technologyChallenges: [
      'Website and application uptime during high-concurrency events',
      'Real-time customer communication across multiple channels',
      'Cloud scalability and elasticity',
      'Integrating logistics APIs with customer-facing apps',
    ],
    recommendedProducts: [
      'Airtel Cloud',
      'Airtel IQ Business Connect',
      'Airtel Secure Internet',
      'Airtel IoT',
      'Airtel Data Center Services',
    ],
    discoveryQuestions: [
      'How does your infrastructure handle traffic surges during major festival sales?',
      'What is the impact on revenue if your platform experiences 15 minutes of downtime?',
      'How are you communicating order updates, OTPs, and delivery statuses to customers?',
      'Are you experiencing issues with SMS delivery rates or delays for OTPs?',
      'How do you protect your platform from DDoS attacks and scraping bots?',
      'How are you tracking your delivery fleet and providing real-time visibility to customers?',
      'What is your strategy for optimizing cloud computing costs as your user base grows?',
      'How do you handle customer support queries during peak volumes?',
    ],
    objections: [
      'We are fully hosted on AWS/GCP and don’t need telecom cloud services',
      'We use a global CPaaS provider for SMS and are locked into volume pricing',
      'Our logistics are entirely outsourced to third-party providers (3PL)',
    ],
    salesOpportunities: [
      'High-volume transactional SMS and voice APIs (Airtel IQ)',
      'DDoS protection and clean-pipe internet (Secure Internet)',
      'Data center colocation for hybrid cloud architectures (Nxtra)',
      'Logistics tracking (Airtel IoT)',
    ],
  ),
  const IndustryIntelligence(
    id: 'ind_hospitality',
    industryName: 'Hospitality',
    businessChallenges: [
      'Enhancing guest experience and personalization',
      'Managing operational costs across multiple properties',
      'Staff coordination in large resorts or hotels',
      'Post-pandemic recovery and digital contactless services',
    ],
    technologyChallenges: [
      'Providing flawless, high-speed Wi-Fi to guests',
      'Integrating legacy Property Management Systems (PMS)',
      'In-room entertainment and connectivity',
      'Securing guest data and payment information',
    ],
    recommendedProducts: [
      'Airtel Managed Wi-Fi',
      'Airtel Corporate Postpaid',
      'Airtel IQ Business Connect',
      'Airtel SIP Trunking',
      'Airtel Leased Line',
    ],
    discoveryQuestions: [
      'What is the most common complaint you receive regarding guest Wi-Fi?',
      'How do you manage the bandwidth allocation between guest networks and back-office operations?',
      'How does your staff communicate across large properties or between multiple hotel locations?',
      'Are you looking to implement contactless check-in or digital concierge services?',
      'How do you handle the high costs of maintaining legacy PBX phone systems in every room?',
      'What is your strategy for securing guest payment data across your distributed network?',
      'How do you engage with guests before their arrival and after their departure?',
      'How quickly can you resolve a network outage at a remote resort property?',
    ],
    objections: [
      'Guest Wi-Fi is a sunk cost and we don’t want to invest more into it',
      'We use local internet service providers because they are cheaper for individual hotels',
      'Replacing our legacy PBX systems across all properties is too capital intensive',
    ],
    salesOpportunities: [
      'Guest Wi-Fi modernization (Managed Wi-Fi)',
      'Unified communications replacing PBX (SIP Trunking / CCaaS)',
      'Guest engagement campaigns (Airtel IQ)',
      'Staff mobility (Corporate Postpaid)',
    ],
  ),
  const IndustryIntelligence(
    id: 'ind_government',
    industryName: 'Government',
    businessChallenges: [
      'Citizen service delivery and digital inclusion',
      'Strict budget constraints and procurement cycles',
      'National security and data sovereignty',
      'Inter-departmental coordination and siloes',
    ],
    technologyChallenges: [
      'Connecting remote Gram Panchayats and rural offices',
      'Ensuring absolute data security and localization',
      'Modernizing legacy government IT infrastructure',
      'Handling massive scale for citizen-facing applications',
    ],
    recommendedProducts: [
      'Airtel Data Center Services (Nxtra)',
      'Airtel Secure Internet',
      'Airtel VPN/MPLS',
      'Airtel SD-WAN',
      'Airtel IQ Business Connect',
    ],
    discoveryQuestions: [
      'How are you ensuring secure connectivity between various municipal or state departments?',
      'What challenges are you facing in delivering digital services to remote rural areas?',
      'How do you ensure citizen data remains localized and strictly compliant with national regulations?',
      'What is your strategy for modernizing legacy infrastructure under strict budget constraints?',
      'How do you handle citizen communication and grievance redressal at scale?',
      'How do you protect critical government infrastructure from state-sponsored cyber threats?',
      'Are you facing bandwidth bottlenecks during major citizen enrollment drives or tax periods?',
      'How are you managing the massive data storage requirements for smart city initiatives?',
    ],
    objections: [
      'We are mandated to use government-owned telecom networks (e.g., BSNL)',
      'The procurement and RFP process takes 12-18 months',
      'We cannot move this highly classified data to any external data center',
    ],
    salesOpportunities: [
      'Smart city connectivity and IoT infrastructure',
      'Secure citizen communication portals (Airtel IQ)',
      'Secure government cloud and colocation (Nxtra - MeitY empanelled)',
      'Secure inter-departmental networks (MPLS/SD-WAN)',
    ],
  ),
  const IndustryIntelligence(
    id: 'ind_energy_utilities',
    industryName: 'Energy & Utilities',
    businessChallenges: [
      'Grid modernization and smart metering',
      'Field worker safety in hazardous environments',
      'Regulatory compliance and reporting',
      'Transitioning to renewable energy sources',
    ],
    technologyChallenges: [
      'Connecting millions of endpoints (smart meters) securely',
      'Providing reliable connectivity to remote oil rigs, pipelines, or solar farms',
      'Securing critical national infrastructure against cyberattacks',
      'Real-time data processing for grid load balancing',
    ],
    recommendedProducts: [
      'Airtel IoT',
      'Airtel Secure Internet',
      'Airtel 5G for Enterprise',
      'Airtel SD-WAN',
      'Airtel Corporate Postpaid',
    ],
    discoveryQuestions: [
      'How are you currently managing connectivity for your smart metering rollout?',
      'What happens when a remote substation loses connectivity to the central grid control?',
      'How do you track and ensure the safety of field workers in remote or hazardous locations?',
      'What is your strategy for securing your OT networks against ransomware or sabotage?',
      'Are you experiencing latency issues when monitoring real-time pipeline pressure or grid loads?',
      'How do you connect new renewable energy sites (wind/solar farms) in areas with poor infrastructure?',
      'How are you managing the massive influx of data generated by IoT sensors across your infrastructure?',
    ],
    objections: [
      'Cellular networks are not reliable enough for critical grid infrastructure',
      'Smart meter RF mesh networks are cheaper than cellular IoT',
      'We require highly specialized ruggedized equipment that telcos don’t understand',
    ],
    salesOpportunities: [
      'Smart metering connectivity (Airtel IoT - NB-IoT/4G)',
      'Remote site connectivity (VSAT / SD-WAN)',
      'Critical infrastructure security (Secure Internet / SOC services)',
      'Private 5G for refinery or plant automation',
    ],
  ),

  // ── NEW INDUSTRIES FROM AIRTEL B2B WEBSITE ───────────────────────────────

  const IndustryIntelligence(
    id: 'ind_automotive',
    industryName: 'Automotive',
    overview: 'The Indian automotive industry is undergoing rapid transformation driven by connected vehicles, EV adoption, and smart manufacturing. Airtel partners with OEMs, component manufacturers, and dealership networks to deliver IoT telematics, Private 5G factory automation, and AIS-140 compliant fleet connectivity.',
    businessChallenges: [
      'Connected vehicle and EV ecosystem management at scale',
      'AIS-140 compliance for commercial vehicle fleets',
      'Supply Chain Visibility',
      'Dealership network communication and inventory synchronization',
      'Rising demand for ADAS and autonomous driving capabilities',
      'Workforce Mobility',
    ],
    technologyChallenges: [
      'Dual-profile M2M eSIM connectivity for connected vehicles',
      'Real-time telematics data transmission at low latency',
      'Private 5G for smart factory floor automation',
      'OT/IT network integration in manufacturing environments',
      'EV battery management system (BMS) connectivity and compliance',
      'GPS and precise positioning for fleet and autonomous applications',
    ],
    recommendedProducts: [
      'Airtel IoT Connectivity',
      'Airtel Precise Positioning',
      'Airtel 5G for Enterprise',
      'Airtel Corporate Postpaid',
      'Airtel SD-WAN',
      'Airtel Secure Internet',
    ],
    discoveryQuestions: [
      'How many vehicles in your commercial fleet currently have telematics or AIS-140 connectivity?',
      'What is your current strategy for connected vehicle data management and OTA updates?',
      'Are you deploying any EV models and how are you managing battery monitoring and compliance?',
      'How do you currently connect your manufacturing plant floor to corporate systems?',
      'What level of GPS accuracy do your fleet operations currently require?',
      'Are you exploring Private 5G for your smart factory initiatives?',
    ],
    objections: [
      'Already have a telematics provider managing our fleet connectivity',
      'Our IT team is not ready for IoT-level infrastructure complexity',
      'Private 5G capex seems too high for current budget cycles',
    ],
    salesOpportunities: [
      'AIS-140 compliant eSIM rollout for entire commercial fleet',
      'Private 5G deployment for smart factory automation',
      'Precise Positioning for ADAS-ready vehicle programs',
      'EV ecosystem connectivity and BMS monitoring',
      'Dealership network SD-WAN modernization',
    ],
    keyRegulations: [
      'AIS-140 — Ministry of Road Transport mandate for GPS/emergency alert in commercial vehicles',
      'AIS-156 — Battery Management System standards for electric vehicles',
      'ARAI homologation requirements for connected vehicle components',
    ],
  ),

  const IndustryIntelligence(
    id: 'ind_media_entertainment',
    industryName: 'Media & Entertainment',
    overview: 'Indian media and entertainment companies — from OTT platforms and production houses to broadcasters and gaming firms — require ultra-low latency content delivery, elastic cloud compute for rendering, and resilient global connectivity for live events. Airtel provides edge data centers, CDN infrastructure, and managed security for content protection.',
    businessChallenges: [
      'Massive traffic spikes during live streaming events (sports, awards)',
      'Content delivery latency affecting viewer experience and churn',
      'Digital rights management (DRM) and anti-piracy enforcement',
      'Rising cloud compute costs for media transcoding and rendering',
      'Expanding to international markets requiring global connectivity',
      'Monetization through server-side ad insertion at scale',
    ],
    technologyChallenges: [
      'CDN and edge infrastructure for low-latency content delivery',
      'Adaptive streaming transcoding and packaging at scale',
      'Secure, low-latency global submarine cable routing',
      'Media workflow integration across distributed production teams',
      'DRM encryption and content protection across devices',
      'Managed SD-WAN for remote production and broadcast sites',
    ],
    recommendedProducts: [
      'Airtel Colocation (Nxtra)',
      'Airtel Public Cloud',
      'Airtel Dedicated Internet (ILL)',
      'Airtel Global Voice',
      'Airtel SD-WAN',
      'Airtel Secure Internet',
    ],
    discoveryQuestions: [
      'How do you currently manage content delivery during peak live streaming events and what are your biggest latency challenges?',
      'Where is your primary content processing and transcoding infrastructure hosted today?',
      'Are you experiencing content piracy issues and how are you addressing DRM and access control?',
      'What is your global distribution strategy and how do you connect to international CDN nodes?',
      'How are your remote production teams collaborating and what connectivity challenges do they face?',
      'What is your cloud strategy for handling unpredictable compute demand during major events?',
    ],
    objections: [
      'We already use AWS CloudFront / Akamai for CDN — why switch?',
      'Our content delivery is already managed by our streaming platform vendor',
      'We are too small to justify enterprise data center colocation',
    ],
    salesOpportunities: [
      'Edge colocation for low-latency last-mile content delivery across Tier 2/3 cities',
      'Elastic cloud compute for media transcoding spikes during major events',
      'Global voice and connectivity for international expansion',
      'Managed security for content protection and DRM compliance',
      'SD-WAN for remote production site connectivity',
    ],
    keyRegulations: [
      'TRAI content guidelines and broadcasting regulations',
      'MIB (Ministry of Information and Broadcasting) compliance for OTT platforms',
      'DPDP Act requirements for user data collected by streaming platforms',
    ],
  ),

  const IndustryIntelligence(
    id: 'ind_travel_tourism',
    industryName: 'Travel & Tourism',
    overview: 'The travel and hospitality industry in India requires always-on connectivity across distributed properties, real-time customer engagement, and smart energy management. Airtel enables hotel chains, airlines, travel agencies, and OTAs to deliver seamless guest experiences, personalized communications, and IoT-based operational efficiency.',
    businessChallenges: [
      'Maintaining consistent network uptime across geographically dispersed properties',
      'Personalizing guest communication across pre-booking, stay, and post-stay journeys',
      'Energy cost management across large hospitality properties',
      'Reducing abandoned bookings through timely omnichannel engagement',
      'Workforce coordination across front-of-house and back-of-house teams',
      'Integration of PMS, POS, and CRM systems across properties',
    ],
    technologyChallenges: [
      'Reliable SD-WAN connectivity across remote or resort properties',
      'Guest Wi-Fi management and bandwidth optimization',
      'IoT-based HVAC and energy monitoring for cost reduction',
      'Contact center routing for global customer service',
      'Multi-property VPN for secure internal communication',
      'WhatsApp and omnichannel messaging for guest engagement',
    ],
    recommendedProducts: [
      'Airtel SD-WAN',
      'Airtel Managed Wi-Fi',
      'Airtel IoT Connectivity',
      'Airtel WhatsApp Business',
      'Airtel Contact Center as a Service',
      'Airtel Corporate Postpaid',
      'Airtel VPN/MPLS',
    ],
    discoveryQuestions: [
      'How do you currently manage network connectivity across your properties and what is your uptime SLA?',
      'How are you communicating with guests at each stage of their journey — pre-arrival, during stay, post-checkout?',
      'What is your annual energy spend across properties and do you have any smart monitoring in place?',
      'How do your reservation and front-desk systems connect to your central IT infrastructure?',
      'How do you manage guest Wi-Fi — is it a managed service or handled internally?',
      'What percentage of your customer service interactions happen on WhatsApp or messaging channels?',
    ],
    objections: [
      'Budget constraints: "Hospitality margins are tight — we cannot invest in new technology right now."',
      'Existing contracts: "We are locked into contracts with our current internet and PBX provider."',
      'Complexity concern: "Managing IoT across 50+ properties seems too complex for our IT team."',
    ],
    salesOpportunities: [
      'SD-WAN rollout across multi-property chains for centralized network management',
      'WhatsApp Business for personalized pre-arrival and in-stay guest engagement',
      'IoT-based smart energy management reducing energy costs by up to 15%',
      'Managed Wi-Fi as a service for branded guest connectivity',
      'Contact center modernization for handling high-volume reservation and support calls',
    ],
    keyRegulations: [
      'TRAI regulations on hotel Wi-Fi and broadband service delivery',
      'Data privacy requirements under DPDP Act for guest personal data',
      'Fire safety and emergency communication compliance for large hospitality properties',
    ],
  ),

  const IndustryIntelligence(
    id: 'ind_telecom_carriers',
    industryName: 'Telecom & Carriers',
    overview: 'Airtel\'s wholesale division serves 1,200+ global carrier interconnects and is one of Asia\'s largest wholesale voice and data providers, built on 400,000+ route KM fiber and 34+ submarine cable systems. For Indian ISPs, MVNOs, international carriers entering India, and OTT platforms needing transport capacity, Airtel\'s carrier digital platform and infrastructure represent a compelling network partnership.',
    businessChallenges: [
      'Declining international voice revenue from OTT bypass (WhatsApp, Teams)',
      'IUC regime uncertainty creating P&L volatility for carrier interconnect businesses',
      'High spectrum and network CAPEX making new service launches expensive',
      'Regulatory compliance burden under DoT, TRAI, and state-level licensing',
      'Traffic monetization — converting massive data growth into ARPU growth',
      'International roaming complexity for MVNOs entering India',
    ],
    technologyChallenges: [
      'Last-mile connectivity gaps in rural India for ISP carrier partners',
      'International voice route fraud — CLI spoofing, bypass fraud reducing revenue',
      'Real-time route analytics needed to optimize voice termination costs',
      'Latency on trans-oceanic routes impacting call quality (India-Middle East, India-US)',
      'DLT compliance system integration for A2P messaging on Indian networks',
      'Interoperability with TRAI\'s Digital Intelligence Platform for fraud management',
    ],
    recommendedProducts: [
      'Airtel Global Voice',
      'Airtel Dedicated Internet (ILL)',
      'Airtel Colocation (Nxtra)',
      'Airtel VPN/MPLS',
      'Airtel CPaaS',
      'Airtel 5G for Enterprise',
    ],
    discoveryQuestions: [
      'What is your international voice traffic volume to India and are you seeing OTT erosion or bypass fraud on key routes?',
      'How are you optimizing routing costs for termination traffic — do you have real-time analytics on route performance vs. cost?',
      'For your MVNO or ISP operations, how are you sourcing last-mile connectivity where you don\'t own infrastructure?',
      'What is your current revenue loss from international voice fraud as a percentage of total traffic?',
      'Are you planning any new market entry or service expansion in India in the next 12 months?',
      'How are you managing DLT compliance for A2P messaging traffic carried over Indian networks?',
    ],
    objections: [
      'We work with Tata/BSNL for Indian termination — established incumbents',
      'Your rates are not competitive on our top Asia corridors',
      'DLT compliance is too complex for us to manage as a foreign carrier',
    ],
    salesOpportunities: [
      'Wholesale voice + data bundle with volume pricing for international carriers',
      'MVNO partnership — full network services for carriers seeking Indian presence',
      'Carrier Digital Platform self-service portal for real-time route management',
      'Last-mile ILL for ISP partners expanding to Tier-2/3 cities',
    ],
    keyRegulations: [
      'DoT ILD/NLD licenses — International and national long-distance requirements',
      'TRAI Interconnect Regulations — IUC framework and interconnect quality standards',
      'TRAI TCCCPR 2018 — DLT compliance for A2P commercial communications',
      'Telecom Act 2023 — New licensing and compliance framework',
      'TRAI Prohibition of Unsolicited Commercial Communications — Spam detection obligations',
    ],
  ),
];
