import 'knowledge_models.dart';

final List<ProductIntelligence> productIntelligenceRepo = [
  const ProductIntelligence(
    id: 'prod_corp_postpaid',
    name: 'Airtel Corporate Postpaid',
    overview: 'Enterprise mobile connectivity solution designed for organizations that require centralized management of employee mobile usage, roaming, communication expenses, and workforce connectivity.',
    idealCustomers: [
      'Banking & Financial Services',
      'Retail Chains',
      'Manufacturing Companies',
      'Logistics Organizations',
      'IT Services Firms',
      'Enterprises with 100+ employees',
    ],
    industries: [
      'Banking & Financial Services',
      'Retail',
      'Manufacturing',
      'Logistics',
      'IT & ITES',
      'Healthcare',
      'Hospitality',
      'Energy & Utilities',
    ],
    painPointsSolved: [
      'Rising Telecom Costs',
      'Distributed Workforce',
      'Roaming Management',
      'Mobility Management',
      'Operational Efficiency',
    ],
    businessOutcomes: [
      'Centralized telecom management',
      'Reduced administrative overhead',
      'Better cost visibility',
      'Improved workforce productivity',
      'Simplified roaming management',
    ],
    discoveryQuestions: [
      'How are mobile expenses currently tracked and reconciled across departments?',
      'What percentage of your workforce requires international roaming capabilities?',
      'How do you manage device provisioning for new hires?',
    ],
    objections: [
      'Pricing concerns: "Our current provider offered a cheaper per-GB rate."',
      'Contract lock-in concerns: "We are locked into a multi-year deal with another telco."',
      'Migration complexity: "Porting thousands of numbers will cause massive downtime."',
    ],
    objectionResponses: [
      'Focus on Total Cost of Ownership (TCO) including management portal efficiency and pooled data benefits, not just raw GB pricing.',
      'Propose a phased rollout strategy for new hires or specific departments while waiting for existing contracts to expire.',
      'Highlight Airtel’s dedicated enterprise onboarding team that manages the entire MNP (Mobile Number Portability) process with zero operational downtime.',
    ],
    crossSellOpportunities: [
      'Airtel IQ Business Connect',
      'Airtel Work From Anywhere Solutions',
      'Airtel IoT',
    ],
    elevatorPitch: 'Airtel Corporate Postpaid simplifies enterprise mobility through centralized management, better visibility, and seamless workforce communication.',
    executivePitch: 'Help your organization manage employee connectivity at scale while reducing administrative effort and improving visibility into telecom spending.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_biz_connect',
    name: 'Airtel IQ Business Connect',
    overview: 'A unified communication and engagement platform enabling organizations to connect with employees, customers, and distributed teams more effectively.',
    idealCustomers: [
      'Retail Organizations',
      'Banking Institutions',
      'Logistics Companies',
      'Large Field Sales Organizations',
      'Government',
    ],
    industries: [
      'Retail',
      'Banking & Financial Services',
      'Logistics',
      'Government',
      'Hospitality',
      'Education',
    ],
    painPointsSolved: [
      'Workforce Communication',
      'Distributed Workforce',
      'Customer Engagement',
      'Real-Time Communication',
    ],
    businessOutcomes: [
      'Better communication consistency',
      'Faster information dissemination',
      'Improved workforce engagement',
      'Increased operational efficiency',
    ],
    discoveryQuestions: [
      'How are you currently managing communications between HQ and your distributed field teams?',
      'What tools do your customer-facing employees use to communicate with clients securely?',
      'How are you ensuring compliance and recording for voice calls made by field staff?',
    ],
    objections: [
      'Adoption concerns: "Employees are used to WhatsApp; they won’t download a new app."',
      'Budget concerns: "We don’t have budget for another enterprise communication tool."',
    ],
    objectionResponses: [
      'Emphasize that Airtel IQ integrates seamlessly with existing workflows and ensures corporate data governance which WhatsApp lacks.',
      'Highlight the cost savings from consolidating disparate legacy communication tools into a single platform.',
    ],
    crossSellOpportunities: [
      'Airtel Corporate Postpaid',
      'Airtel Contact Center as a Service',
      'Airtel CPaaS',
    ],
    elevatorPitch: 'Business Connect helps organizations communicate consistently across distributed teams while improving engagement and operational effectiveness.',
    executivePitch: 'Create a single, enterprise-ready communication layer that scales across your workforce and locations securely.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_sdwan',
    name: 'Airtel SD-WAN',
    overview: 'Software-Defined Wide Area Network solution providing intelligent routing, centralized management, and secure connectivity across distributed enterprise branches.',
    idealCustomers: [
      'Multi-branch Retailers',
      'Banking & Financial Institutions',
      'Manufacturing Companies with multiple plants',
      'Logistics Hubs',
    ],
    industries: [
      'Banking & Financial Services',
      'Retail',
      'Manufacturing',
      'Logistics',
      'IT & ITES',
      'Government',
    ],
    painPointsSolved: [
      'Branch Connectivity',
      'Application Performance',
      'Network Visibility',
      'Rising Telecom Costs',
      'Legacy Systems',
    ],
    businessOutcomes: [
      'Reduced MPLS dependency and costs',
      'Optimized cloud application performance',
      'Centralized network visibility and control',
      'Rapid branch provisioning',
    ],
    discoveryQuestions: [
      'How are you currently routing traffic from your branches to cloud applications (e.g., Office 365, AWS)?',
      'What is your average timeline to provision network connectivity for a new branch location?',
      'How much visibility do you have into branch-level application performance and bandwidth utilization?',
    ],
    objections: [
      'Migration complexity: "Ripping out our MPLS routers is too risky for branch uptime."',
      'Security concerns: "Using broadband internet for branch traffic isn\'t secure enough for our data."',
      'Vendor consolidation: "We prefer to buy SD-WAN hardware directly from OEM vendors like Cisco/Fortinet."',
    ],
    objectionResponses: [
      'Airtel SD-WAN can be deployed in a hybrid model, running alongside existing MPLS during a phased migration.',
      'Highlight built-in Next-Generation Firewall (NGFW) and IPsec encryption capabilities securing broadband links.',
      'Explain the benefits of Airtel’s fully managed service (underlay + overlay + management portal) with a single SLA.',
    ],
    crossSellOpportunities: [
      'Airtel Secure Internet',
      'Airtel Cloud',
      'Airtel Leased Line',
    ],
    elevatorPitch: 'Airtel SD-WAN intelligently routes your branch traffic to optimize application performance while reducing reliance on expensive legacy links.',
    executivePitch: 'Modernize your enterprise network architecture to be cloud-first, gaining centralized visibility and agility while driving down total network costs.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_secure_internet',
    name: 'Airtel Secure Internet',
    overview: 'Enterprise-grade internet leased line bundled with advanced cybersecurity features including DDoS protection, firewall, and content filtering from the network edge.',
    idealCustomers: [
      'E-Commerce Platforms',
      'IT & ITES Companies',
      'Educational Institutions',
      'Government Agencies',
      'Healthcare Providers',
    ],
    industries: [
      'IT & ITES',
      'E-Commerce',
      'Government',
      'Education',
      'Healthcare',
      'Banking & Financial Services',
    ],
    painPointsSolved: [
      'Security & Compliance',
      'Business Continuity',
      'Regulatory Compliance',
    ],
    businessOutcomes: [
      'Protection against volumetric DDoS attacks',
      'Clean pipe internet delivery',
      'Simplified security management without on-premise hardware',
      'Guaranteed uptime SLAs',
    ],
    discoveryQuestions: [
      'What is the financial impact of your public-facing applications going offline due to a DDoS attack?',
      'How are you currently managing firewall rules and content filtering across your locations?',
      'Are you struggling with the CAPEX required to continuously upgrade on-premise security appliances?',
    ],
    objections: [
      'Existing hardware: "We just bought new on-premise firewalls."',
      'Performance: "Will deep packet inspection slow down our internet speeds?"',
    ],
    objectionResponses: [
      'Secure Internet operates upstream at the ISP level, blocking volumetric DDoS attacks before they ever reach and overwhelm your on-premise firewalls.',
      'Airtel provisions the compute resources at the edge to ensure security filtering happens at wire-speed without adding latency.',
    ],
    crossSellOpportunities: [
      'Airtel SD-WAN',
      'Airtel Data Center Services',
      'Airtel Cloud',
    ],
    elevatorPitch: 'Airtel Secure Internet delivers high-speed connectivity with enterprise-grade cybersecurity built directly into the network pipe.',
    executivePitch: 'Shift your security perimeter to the Airtel network edge, protecting your business from massive cyber threats without the heavy CAPEX of on-premise hardware.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_cloud',
    name: 'Airtel Cloud',
    overview: 'Comprehensive suite of public, private, and edge cloud solutions tailored for Indian enterprises, offering data localization and high-performance compute.',
    idealCustomers: [
      'Startups and E-Commerce',
      'Government Departments',
      'Healthcare Providers',
      'Manufacturing Firms',
    ],
    industries: [
      'IT & ITES',
      'E-Commerce',
      'Government',
      'Healthcare',
      'Manufacturing',
      'Education',
    ],
    painPointsSolved: [
      'Cloud Migration',
      'Regulatory Compliance',
      'Digital Transformation',
      'Legacy Systems',
    ],
    businessOutcomes: [
      'Strict data sovereignty and localization',
      'Scalable compute and storage resources',
      'Reduced latency via edge cloud locations',
      'Lower egress costs compared to hyperscalers',
    ],
    discoveryQuestions: [
      'What are your primary concerns regarding data residency and local compliance mandates?',
      'How unpredictable are your current cloud billing and data egress costs?',
      'What legacy applications are you struggling to migrate to public cloud environments?',
    ],
    objections: [
      'Hyperscaler lock-in: "We are heavily invested in AWS/Azure ecosystems."',
      'Feature parity: "Do you have all the PaaS services that major public clouds offer?"',
      'Data residency concerns: "Are your cloud servers physically located in India?"',
    ],
    objectionResponses: [
      'Position Airtel Cloud as a multi-cloud or hybrid strategy partner, specifically for workloads requiring strict Indian data localization or low egress costs.',
      'Focus on Infrastructure as a Service (IaaS) stability, edge compute capabilities, and bespoke managed services rather than competing directly on PaaS breadth.',
      'Affirm that Airtel Cloud is 100% hosted in India (Nxtra Data Centers), fully compliant with government data sovereignty mandates.',
    ],
    crossSellOpportunities: [
      'Airtel Data Center Services',
      'Airtel Secure Internet',
      'Airtel VPN/MPLS',
    ],
    elevatorPitch: 'Airtel Cloud provides highly secure, localized, and cost-effective cloud infrastructure to power your digital transformation.',
    executivePitch: 'Leverage a cloud platform that guarantees Indian data sovereignty, eliminates unpredictable egress fees, and provides edge computing performance for your critical applications.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_iot',
    name: 'Airtel IoT',
    overview: 'End-to-end Internet of Things connectivity and management platform supporting NB-IoT, 4G, and 5G for smart metering, asset tracking, and industrial automation.',
    idealCustomers: [
      'Energy Utilities',
      'Logistics & Supply Chain',
      'Automotive Manufacturers',
      'Smart City Projects',
    ],
    industries: [
      'Energy & Utilities',
      'Logistics',
      'Manufacturing',
      'Government',
      'Healthcare',
    ],
    painPointsSolved: [
      'Operational Efficiency',
      'Network Visibility',
      'Business Continuity',
    ],
    businessOutcomes: [
      'Real-time asset tracking and visibility',
      'Automated meter reading and smart grid management',
      'Predictive maintenance for industrial machinery',
      'Centralized connectivity management via IoT Hub',
    ],
    discoveryQuestions: [
      'How are you currently tracking the location and status of your high-value assets in transit?',
      'What connectivity challenges are you facing with your smart meter rollout in rural areas?',
      'How do you manage the lifecycle, activation, and billing of thousands of deployed IoT SIMs?',
    ],
    objections: [
      'Coverage issues: "Cellular networks are unreliable in the remote areas where our assets travel."',
      'Hardware integration: "Our sensors aren’t compatible with your network protocols."',
      'Scale management: "Managing 100,000 SIMs sounds like an administrative nightmare."',
    ],
    objectionResponses: [
      'Highlight Airtel’s extensive NB-IoT (Narrowband IoT) coverage designed specifically for deep indoor and remote penetration.',
      'Airtel IoT provides an agnostic platform with extensive device certification support and global eSIM (eUICC) capabilities.',
      'Demonstrate the Airtel IoT Hub portal which allows bulk provisioning, automated rules, and real-time diagnostics at massive scale.',
    ],
    crossSellOpportunities: [
      'Airtel 5G for Enterprise',
      'Airtel Cloud',
      'Airtel SD-WAN',
    ],
    elevatorPitch: 'Airtel IoT provides reliable, secure connectivity and centralized management for millions of connected devices across your enterprise.',
    executivePitch: 'Unlock new operational efficiencies and revenue streams by securely connecting and managing your physical assets, powered by India’s largest IoT network.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_sip_trunking',
    name: 'Airtel SIP Trunking',
    overview: 'Scalable and secure IP-based voice connectivity solution replacing legacy ISDN/PRI lines for enterprise PBX and contact centers.',
    idealCustomers: [
      'BPO & Call Centers',
      'Large Corporate Offices',
      'Hospitality Chains',
      'Educational Institutions',
    ],
    industries: [
      'IT & ITES',
      'Hospitality',
      'Education',
      'Banking & Financial Services',
      'Retail',
    ],
    painPointsSolved: [
      'Rising Telecom Costs',
      'Legacy Systems',
      'Contact Center Modernization',
      'Business Continuity',
    ],
    businessOutcomes: [
      'Significant reduction in voice calling costs',
      'Elimination of physical PRIs and hardware maintenance',
      'Rapid scalability of voice channels during peak seasons',
      'Improved disaster recovery with IP routing',
    ],
    discoveryQuestions: [
      'Are you still managing physical ISDN/PRI lines across your multiple office locations?',
      'How difficult is it to scale up your voice channels during a sudden spike in call center traffic?',
      'What is your disaster recovery plan if the physical phone lines to your main building are cut?',
    ],
    objections: [
      'Quality concerns: "Voice over IP (VoIP) drops calls and has jitter."',
      'Legacy PBX constraints: "Our current PBX system doesn’t support SIP."',
      'Regulatory concerns: "Is SIP routing compliant with DoT/TRAI regulations?"',
    ],
    objectionResponses: [
      'Airtel SIP Trunking runs over dedicated enterprise leased lines with strict Quality of Service (QoS) guarantees, unlike internet-based VoIP.',
      'Airtel can provide a managed gateway (SBC) to convert SIP signals to legacy formats until you upgrade your PBX.',
      'Airtel SIP Trunking is fully compliant with Indian telecom regulations, including logical partitioning requirements for OSP/BPOs.',
    ],
    crossSellOpportunities: [
      'Airtel Contact Center as a Service',
      'Airtel Leased Line',
      'Airtel SD-WAN',
    ],
    elevatorPitch: 'Airtel SIP Trunking modernizes your enterprise voice infrastructure, cutting costs and enabling instant scalability.',
    executivePitch: 'Retire expensive legacy phone lines and migrate to a resilient, IP-based voice architecture that scales dynamically with your business needs.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_ccaas',
    name: 'Airtel Contact Center as a Service',
    overview: 'Cloud-based omnichannel contact center solution that eliminates the need for on-premise dialers and PBX hardware.',
    idealCustomers: [
      'E-Commerce Support Teams',
      'Banking Helpdesks',
      'Healthcare Appointment Centers',
      'Outsourced BPOs',
    ],
    industries: [
      'E-Commerce',
      'Banking & Financial Services',
      'Healthcare',
      'IT & ITES',
      'Retail',
    ],
    painPointsSolved: [
      'Contact Center Modernization',
      'Customer Engagement',
      'Remote Work',
      'Legacy Systems',
    ],
    businessOutcomes: [
      'Enable agents to work from anywhere with just a browser',
      'Omnichannel integration (Voice, Chat, Email, Social)',
      'Zero CAPEX on dialer hardware',
      'Advanced analytics and AI-driven call routing',
    ],
    discoveryQuestions: [
      'How are you currently managing customer support queries across voice, email, and social media?',
      'What were the challenges you faced transitioning your call center agents to work-from-home?',
      'How much are you spending on annual maintenance contracts (AMCs) for your on-premise dialer?',
    ],
    objections: [
      'Voice quality for remote agents: "Home broadband isn’t reliable enough for voice support."',
      'Data security: "We can’t have customer data accessible from agents’ personal laptops."',
    ],
    objectionResponses: [
      'Bundle CCaaS with Airtel Work From Anywhere solutions (dedicated broadband/LTE routers) to guarantee QoS.',
      'The cloud platform is strictly role-based and data remains centralized; no customer data is stored locally on the agent’s machine.',
    ],
    crossSellOpportunities: [
      'Airtel SIP Trunking',
      'Airtel Work From Anywhere Solutions',
      'Airtel CPaaS',
    ],
    elevatorPitch: 'Airtel CCaaS moves your contact center to the cloud, enabling an omnichannel customer experience and empowering agents to work from anywhere.',
    executivePitch: 'Modernize customer service by replacing rigid on-premise hardware with an agile, scalable cloud contact center that reduces CAPEX and improves customer satisfaction.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_managed_wifi',
    name: 'Airtel Managed Wi-Fi',
    overview: 'Enterprise-grade, fully managed wireless networking solution covering hardware provisioning, deployment, monitoring, and guest analytics.',
    idealCustomers: [
      'Universities and Campuses',
      'Hotel Chains and Resorts',
      'Large Retail Chains',
      'Warehousing and Logistics Facilities',
    ],
    industries: [
      'Education',
      'Hospitality',
      'Retail',
      'Logistics',
      'Healthcare',
    ],
    painPointsSolved: [
      'Operational Efficiency',
      'Customer Engagement',
      'Network Visibility',
    ],
    businessOutcomes: [
      'Seamless, dead-zone-free campus connectivity',
      'Monetizable guest Wi-Fi portals with analytics',
      'Zero IT overhead for managing access points',
      'Secure segregation of corporate and guest traffic',
    ],
    discoveryQuestions: [
      'How much time does your IT team spend troubleshooting Wi-Fi dead zones and complaints?',
      'Are you able to capture marketing data or run promotions through your current guest Wi-Fi portal?',
      'How do you manage the massive density of connected devices during large events or in lecture halls?',
    ],
    objections: [
      'Cost: "We prefer to buy consumer-grade routers locally to save money."',
      'Control: "Our IT team wants full administrative control over the network hardware."',
    ],
    objectionResponses: [
      'Consumer routers fail under enterprise density and lack security protocols, resulting in high hidden maintenance costs and security breaches.',
      'Airtel provides a comprehensive cloud dashboard giving your IT team full visibility and control, while we handle the underlying hardware SLAs.',
    ],
    crossSellOpportunities: [
      'Airtel Leased Line',
      'Airtel SD-WAN',
      'Airtel Secure Internet',
    ],
    elevatorPitch: 'Airtel Managed Wi-Fi delivers a flawless wireless experience for employees and guests without burdening your IT staff.',
    executivePitch: 'Transform your campus or retail spaces with secure, high-density Wi-Fi that provides actionable customer analytics and operates under a single SLA.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_mpls',
    name: 'Airtel VPN/MPLS',
    overview: 'Highly secure, private Multiprotocol Label Switching (MPLS) network connecting enterprise branches with guaranteed latency and Quality of Service (QoS).',
    idealCustomers: [
      'Government Departments',
      'Banks and Financial Institutions',
      'Large Manufacturing Conglomerates',
    ],
    industries: [
      'Government',
      'Banking & Financial Services',
      'Manufacturing',
      'Energy & Utilities',
    ],
    painPointsSolved: [
      'Security & Compliance',
      'Application Performance',
      'Branch Connectivity',
      'Regulatory Compliance',
    ],
    businessOutcomes: [
      'Absolute data privacy isolated from the public internet',
      'Guaranteed bandwidth for mission-critical applications (e.g., SAP, Core Banking)',
      'Predictable latency across regional branches',
      'High network availability',
    ],
    discoveryQuestions: [
      'How are you ensuring the absolute privacy of data transmitted between your core data center and regional branches?',
      'Do you experience application timeouts with your ERP or core banking software over standard internet connections?',
      'What are your compliance mandates regarding data transmission over public networks?',
    ],
    objections: [
      'Cost and rigidity: "MPLS is too expensive and takes months to provision compared to broadband SD-WAN."',
      'Cloud shift: "Most of our apps are in the public cloud now, we don\'t need private branch-to-branch routing."',
    ],
    objectionResponses: [
      'Position a hybrid architecture: Keep MPLS for the highly sensitive/critical core sites and use Airtel SD-WAN over broadband for smaller, agile branches.',
      'Airtel MPLS integrates seamlessly with Airtel Cloud and direct hyperscaler connects (ExpressRoute/DirectConnect) to ensure private cloud access.',
    ],
    crossSellOpportunities: [
      'Airtel SD-WAN',
      'Airtel Data Center Services',
      'Airtel SIP Trunking',
    ],
    elevatorPitch: 'Airtel MPLS provides the most secure, predictable, and private network backbone for your mission-critical enterprise applications.',
    executivePitch: 'Protect your sensitive data and guarantee ERP performance by running your core business operations on India’s most robust private enterprise network.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_wfa',
    name: 'Airtel Work From Anywhere Solutions',
    overview: 'Integrated connectivity and security bundles (4G/LTE routers, secure broadband, endpoint security) enabling a secure remote workforce.',
    idealCustomers: [
      'IT & ITES (BPOs, KPOs)',
      'Consulting Firms',
      'Financial Services Call Centers',
    ],
    industries: [
      'IT & ITES',
      'Banking & Financial Services',
      'Education',
      'Telecom',
    ],
    painPointsSolved: [
      'Remote Work',
      'Distributed Workforce',
      'Security & Compliance',
      'Business Continuity',
    ],
    businessOutcomes: [
      'Guaranteed productivity for remote employees',
      'Corporate-grade security enforced at the employee’s home',
      'Centralized billing for remote connectivity stipends',
      'Rapid deployment for new remote hires',
    ],
    discoveryQuestions: [
      'How do you ensure reliable internet access for your critical remote support agents?',
      'Are you currently reimbursing employees for their personal home broadband, and is that difficult to manage?',
      'How do you prevent unauthorized devices in an employee’s home from accessing the corporate network?',
    ],
    objections: [
      'Reimbursement is easier: "We just give employees a fixed allowance to buy their own internet."',
      'Coverage issues: "Not all employees have Airtel coverage at home."',
    ],
    objectionResponses: [
      'Allowances don’t guarantee the employee purchases a reliable connection, leading to dropped client calls and security vulnerabilities.',
      'Airtel provides a mix of FTTH (Fiber) and enterprise-grade 4G/LTE routers to ensure connectivity regardless of fiber availability.',
    ],
    crossSellOpportunities: [
      'Airtel Contact Center as a Service',
      'Airtel Corporate Postpaid',
      'Airtel Secure Internet',
    ],
    elevatorPitch: 'Airtel Work From Anywhere provides secure, managed connectivity directly to your employees’ homes, ensuring corporate security and productivity.',
    executivePitch: 'Standardize your remote work infrastructure with enterprise-grade connectivity and security, eliminating the risks and inefficiencies of consumer home broadband.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_nxtra',
    name: 'Airtel Data Center Services (Nxtra)',
    overview: 'Tier-III and Tier-IV hyperscale and edge data center colocation services providing high-density power, cooling, and extreme physical security.',
    idealCustomers: [
      'Cloud Service Providers',
      'Banking and Insurance Companies',
      'Government Departments',
      'Large E-Commerce Platforms',
    ],
    industries: [
      'IT & ITES',
      'Government',
      'Banking & Financial Services',
      'E-Commerce',
      'Telecom',
    ],
    painPointsSolved: [
      'Legacy Systems',
      'Regulatory Compliance',
      'Business Continuity',
      'Digital Transformation',
    ],
    businessOutcomes: [
      'Eliminate CAPEX of building and maintaining private data centers',
      'Ensure 99.99% uptime for critical hardware infrastructure',
      'Achieve strict compliance with Indian data sovereignty laws',
      'Direct, low-latency access to Airtel’s global network backbone',
    ],
    discoveryQuestions: [
      'What is the current capacity utilization of your on-premise data center, and are you running out of power/cooling?',
      'How much capital is tied up in maintaining and upgrading your physical server rooms?',
      'What is your disaster recovery (DR) strategy, and how far apart are your Primary and DR sites?',
    ],
    objections: [
      'Public cloud shift: "We are moving everything to AWS; we don’t need colocation anymore."',
      'Security control: "We prefer to keep our servers on our own premises where we can see them."',
    ],
    objectionResponses: [
      'Highlight hybrid cloud architectures: Nxtra hosts hyperscaler outposts (AWS Outposts, Azure Stack) allowing you to maintain legacy hardware adjacent to your public cloud workloads.',
      'Nxtra facilities offer higher physical security (7-layer security, biometrics) and redundancy than 99% of private enterprise server rooms.',
    ],
    crossSellOpportunities: [
      'Airtel Cloud',
      'Airtel VPN/MPLS',
      'Airtel Secure Internet',
    ],
    elevatorPitch: 'Nxtra by Airtel offers world-class data center colocation, providing the power, security, and network density to house your critical IT infrastructure.',
    executivePitch: 'Free up capital and real estate by shifting your IT infrastructure to India’s largest and most secure network of hyper-scale and edge data centers.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_private_5g',
    name: 'Airtel 5G for Enterprise',
    overview: 'Captive Non-Public Network (Private 5G) providing ultra-reliable, low-latency, and high-bandwidth wireless connectivity tailored for industrial automation and IoT.',
    idealCustomers: [
      'Automotive Manufacturers',
      'Mining Operations',
      'Large Ports and Logistics Hubs',
      'Smart Factories (Industry 4.0)',
    ],
    industries: [
      'Manufacturing',
      'Logistics',
      'Energy & Utilities',
      'Government',
    ],
    painPointsSolved: [
      'Operational Efficiency',
      'Legacy Systems',
      'Network Visibility',
      'Business Continuity',
    ],
    businessOutcomes: [
      'Enable real-time robotics and Automated Guided Vehicles (AGVs)',
      'Wire-like reliability without the physical constraints of cabling',
      'Massive IoT sensor density on the factory floor',
      'Absolute data privacy (data never leaves the premises)',
    ],
    discoveryQuestions: [
      'Are your current Wi-Fi networks struggling with latency or interference on the factory floor?',
      'How are you planning to connect autonomous vehicles or robotics across your manufacturing campus?',
      'What is the cost of rewiring your facility every time you need to reconfigure the assembly line?',
    ],
    objections: [
      'Cost: "Private 5G is too expensive and experimental right now."',
      'Wi-Fi 6 alternative: "We are upgrading to Wi-Fi 6, which should solve our bandwidth issues."',
    ],
    objectionResponses: [
      'Frame the ROI around operational uptime and the flexibility to reconfigure assembly lines without cabling costs.',
      'Wi-Fi 6 struggles with handoffs for fast-moving objects (like AGVs) and suffers from interference in metal-heavy industrial environments; 5G handles this flawlessly.',
    ],
    crossSellOpportunities: [
      'Airtel IoT',
      'Airtel Cloud (Edge Compute)',
      'Airtel SD-WAN',
    ],
    elevatorPitch: 'Airtel Private 5G unleashes Industry 4.0 by providing ultra-low latency, secure, and interference-free wireless connectivity for your critical operations.',
    executivePitch: 'Future-proof your industrial operations with a dedicated 5G network that enables advanced automation, robotics, and massive IoT scaling.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_cpaas',
    name: 'Airtel CPaaS',
    overview: 'Communications Platform as a Service providing API-driven SMS, Voice, and WhatsApp integration directly into enterprise applications and workflows.',
    idealCustomers: [
      'E-Commerce Applications',
      'Fintech and Banking Apps',
      'Aggregator Platforms (Ride-sharing, Food Delivery)',
      'Logistics Tracking Platforms',
    ],
    industries: [
      'E-Commerce',
      'Banking & Financial Services',
      'IT & ITES',
      'Logistics',
      'Retail',
    ],
    painPointsSolved: [
      'Customer Engagement',
      'Digital Transformation',
      'Real-Time Communication',
    ],
    businessOutcomes: [
      'Automated OTP delivery and transactional alerts',
      'Rich conversational commerce via WhatsApp Business API',
      'Call masking for privacy between delivery drivers and customers',
      'Direct-to-telco routing ensuring high delivery rates and low latency',
    ],
    discoveryQuestions: [
      'How are you currently sending OTPs, and what is your SMS delivery failure rate?',
      'Are you exploring WhatsApp as a channel for customer support or conversational commerce?',
      'How do you protect customer phone numbers when your delivery agents need to call them?',
    ],
    objections: [
      'Developer adoption concerns: "Our developers prefer using global APIs like Twilio."',
      'Integration concerns: "It will take too long to rewrite our communication logic."',
    ],
    objectionResponses: [
      'Airtel CPaaS offers modern, RESTful APIs identical in ease-of-use to global players, but with the distinct advantage of direct, zero-hop routing on the Airtel network for higher delivery success in India.',
      'We provide robust SDKs and comprehensive documentation, ensuring integration can be completed in days, not months.',
    ],
    crossSellOpportunities: [
      'Airtel IQ Business Connect',
      'Airtel Contact Center as a Service',
      'Airtel Secure Internet',
    ],
    elevatorPitch: 'Airtel CPaaS embeds powerful SMS, Voice, and WhatsApp capabilities directly into your applications to automate and enhance customer engagement.',
    executivePitch: 'Drive superior customer experiences and higher transaction completion rates by utilizing Airtel’s direct, carrier-grade communication APIs.',
    meetingTalkingPoints: [],
  ),
  const ProductIntelligence(
    id: 'prod_leased_line',
    name: 'Airtel Leased Line (ILL)',
    overview: 'Internet Leased Line providing dedicated, uncontended, and symmetric internet bandwidth with high uptime SLAs for enterprise offices.',
    idealCustomers: [
      'Corporate Headquarters',
      'Software Development Centers',
      'Media and Production Houses',
      'Hospitals',
    ],
    industries: [
      'IT & ITES',
      'Healthcare',
      'Education',
      'Banking & Financial Services',
      'Government',
      'Manufacturing',
    ],
    painPointsSolved: [
      'Application Performance',
      'Business Continuity',
      'Branch Connectivity',
    ],
    businessOutcomes: [
      'Symmetrical upload and download speeds for cloud applications',
      '1:1 dedicated bandwidth (no sharing with other businesses)',
      'Enterprise-grade Service Level Agreements (SLAs) for uptime',
      'Static IPs for hosting internal applications securely',
    ],
    discoveryQuestions: [
      'Are your employees experiencing lag or dropped connections during critical video conferences?',
      'How much productivity is lost when your office internet connection slows down during peak hours?',
      'Do you need high upload speeds for backing up large data sets to the cloud?',
    ],
    objections: [
      'Pricing concerns: "Business broadband is a fraction of the cost of a Leased Line."',
      'Redundancy concerns: "What happens if the fiber gets cut?"',
    ],
    objectionResponses: [
      'Broadband is heavily contended (shared) and asymmetrical (poor upload speeds). ILL is dedicated 1:1 bandwidth backed by financial SLAs.',
      'Airtel provisions dual-path redundancy with auto-failover (e.g., secondary RF link) to ensure uninterrupted connectivity even if primary fiber is cut.',
    ],
    crossSellOpportunities: [
      'Airtel Secure Internet',
      'Airtel SD-WAN',
      'Airtel SIP Trunking',
      'Airtel Managed Wi-Fi',
    ],
    elevatorPitch: 'Airtel Internet Leased Line provides the dedicated, high-speed, and reliable foundation necessary for modern cloud-based enterprise operations.',
    executivePitch: 'Ensure your business never stops running with enterprise-grade, dedicated internet access backed by industry-leading SLAs and dual-path redundancy.',
    meetingTalkingPoints: [],
  ),
];
