"""add rbac fields

Revision ID: c3107a15aaab
Revises: 3538d027b011
Create Date: 2026-06-06 23:04:19.018190

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import uuid

revision = 'c3107a15aaab'
down_revision = '3538d027b011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_customers_owner_id'), 'customers', ['owner_id'], unique=False)
    op.create_foreign_key(op.f('fk_customers_owner_id_users'), 'customers', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_manager_id'), 'users', ['manager_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_manager_id_users'), 'users', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Seed initial roles
    roles = ["account_manager", "zonal_sales_manager", "circle_business_head", "admin"]
    for r in roles:
        role_id = str(uuid.uuid4())
        op.execute(f"INSERT INTO roles (id, name, created_at, updated_at) VALUES ('{role_id}', '{r}', now(), now()) ON CONFLICT (name) DO NOTHING")
    
    # Assign default role 'account_manager' to existing users without roles
    op.execute("""
        INSERT INTO user_roles (user_id, role_id)
        SELECT u.id, r.id 
        FROM users u 
        CROSS JOIN roles r 
        WHERE r.name = 'account_manager' 
        AND NOT EXISTS (
            SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id
        )
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_manager_id_users'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_manager_id'), table_name='users')
    op.drop_column('users', 'manager_id')
    op.drop_constraint(op.f('fk_customers_owner_id_users'), 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_owner_id'), table_name='customers')
    op.drop_column('customers', 'owner_id')
    # ### end Alembic commands ###
